Merged PR 526871: Fix $compute with enum
Compute on entity with Enum field(s) throws error.
To reproduce #1641887, I added an Enum field to the test Model `SelectExpandTestCustomer` which is used in `ComputeTests.cs`. The existing tests started to fail with this error:
```
System.InvalidOperationException : The EDM instance of type '[Microsoft.AspNet.OData.Test.SelectExpandTestCustomer Nullable=True]' is missing the property 'Gender'.
  ```
which is similar to error we see in AzureDevOps:
```
System.InvalidOperationException: The EDM instance of type '[Microsoft.VisualStudio.Services.Analytics.Model.WorkItemBoardSnapshot Nullable=True]' is missing the property 'IsLastDayOfPeriod'.
```

Related work items: #1641887